More warnings for new packagers.

diff --git a/packaging/fireRhinerpms b/packaging/fireRhinerpms
--- a/packaging/fireRhinerpms
+++ b/packaging/fireRhinerpms
@@ -1,24 +1,29 @@
 #!/bin/sh
-# This is a script for developers with repo access to generate rpm from bare checkouts.
-# It replaces (i.e. violates, of necessity) the normal split-responsibility model of
+# This is a script for developers with repo access to generate rpm from
+# bare checkouts.
+# It replaces (i.e. violates, of necessity) the normal split-responsibility 
+# model of
 # 1) project release ready to use source tar ball where ./configure is working.
-# 2) independent product packager/distribution manager/vendor adds in spec file wisdom/value.
+# 2) independent product packager/distribution manager/vendor adds in spec 
+#     file wisdom/value.
 # This leads to some Rube Goldbergism, as should be expected.
 # 
 # It is specific to the way we run on certain DOE machines.
 # You are free to copy it to other names and tune it to your systems.
-# You may also need to make your own (differently named) ./util/release_tarball-300-rhine.sh
+# You may also need to make your own (differently named) 
+#    ./util/release_tarball-300-rhine.sh
 # replacement, in particular if you want to pull a specific repository branch.
 # Please note:
-# configuration options later in this scripts affect the source tar ball generated.
+# Configuration options later in this script affect the source tar ball generated by make dist, so you cannot optimize away the double invocation of configure.
 #
-# correct checkout tests:
+# Correct checkout tests:
 bad=0
 if ! test -f sos/configure.ac; then
 	echo "you need to get sos in place before running this. try:"
 	echo "git submodule init sos"
 	echo "git submodule update sos"
 	echo "or copying manually to populate sos/"
+	echo "The git commands will NOT work from a github zip download"
 	bad=1
 fi
 if ! test -f gpcd-support/configure.ac; then
@@ -26,6 +31,7 @@ if ! test -f gpcd-support/configure.ac; then
 	echo "git submodule init gpcd-support"
 	echo "git submodule update gpcd-support"
 	echo "or copying manually to populate gpcd-support/"
+	echo "The git commands will NOT work from a github zip download"
 	bad=1
 fi
 # cheesy tests, very suse/cray specific
@@ -55,7 +61,10 @@ fi
 ./configure --enable-ssl --disable-rpath --disable-readline CC=gcc CXX=g++ --enable-sos --enable-swig --with-pkglibdir=ovis-ldms --enable-gpcdlocal --enable-aries-mmr
 mkdir -p Release
 rm -rf Release/*
-./util/release_tarball-300-rhine.sh
+if ! ./util/release_tarball-300-rhine.sh; then
+	echo "util/release_tarball-300-rhine.sh failed"
+	exit 1
+fi
 cd Release
 echo "============================= bundle done ============="
 tar zxf ovis-3.3.2.tar.gz
